spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: BlogPlatform


  datasource:
    url: jdbc:mysql://34.47.113.98:3306/soundstudio
    username: soundstudio
#    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: k32h7cOaxVR9BZC6n4GFm2ZPX6aYQ9v3
    refresh: k32h7cOaxVR9BZC6n4GFm2ZPX6aYQ9v3